[build]
  publish = "site/_site"
  command = "cd site && bundle install && bundle exec jekyll build"

[build.environment]
  JEKYLL_ENV = "production"
  RUBY_VERSION = "3.1.0"

[[redirects]]
  from = "/about"
  to = "/pages/about/"
  status = 301

[[redirects]]
  from = "/privacy"
  to = "/pages/privacy/"
  status = 301

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"