# Jekyll/GitHub Pages Configuration
title: "AutoBlog"
description: "AI-generated content for modern digital life"
baseurl: ""
url: "https://autoblog-pipe.netlify.app"

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Permalinks
permalink: /:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "AutoBot"
  - scope:
      path: "pages"
      type: "pages"
    values:
      layout: "page"

# SEO
author: AutoBot
twitter_username: 
github_username: grayson1999

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - gemfiles
  - .git
  - .github

# Include pages directory
include:
  - pages

# Collections
collections:
  posts:
    output: true

# Google Analytics (placeholder)
# google_analytics: UA-XXXXXXXX-X

# AdSense (placeholder for later)
# adsense_client: ca-pub-XXXXXXXXXXXXXXXX